spring:
  profiles:
    active: dev
  application:
    name: stock-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none

