cors:
  allowed-origins: "http://localhost:5173"

spring:
  liquibase:
    clear-checksums: true
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_tech_test
    username: myuser
    password: mypassword

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type:
          descriptor:
            sql:
              basic: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE