cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}